export const portfolioProjects = [
  {
    slug: 'trabalengua',
    stack: ["React (CRA + craco)", "Tailwind CSS + shadcn/ui", "Cloudflare Workers", "Cloudflare R2", "Autenticación con token HMAC"],
    challenge: "La tienda necesitaba vender uniformes de varios colegios a la vez: cada establecimiento tiene sus propias prendas, y cada prenda maneja tallas con stock independiente. Además, el equipo debía poder actualizar catálogo, precios y pedidos sin depender de un programador.",
    sections: [["Frontend en React", "Aplicación de página única construida con React, Tailwind CSS y componentes shadcn/ui. El catálogo se navega por colegio, luego por prenda y finalmente por talla, mostrando solo las variantes con stock disponible."], ["API sobre Cloudflare Workers", "Un Worker actúa como router: atiende la API de la tienda y del panel (/api), sirve las imágenes (/media) y entrega los estáticos del SPA con fallback a index.html para las rutas del cliente."], ["Persistencia en R2", "Catálogo y pedidos se guardan como documentos JSON en un bucket de Cloudflare R2, junto con las fotos de producto. Esto elimina la necesidad de un servidor de base de datos y mantiene los costos de operación muy bajos."], ["Panel de administración propio", "Acceso protegido con login y token firmado (HMAC). Desde el panel se crean colegios y prendas, se ajusta el stock por talla y se revisan los pedidos registrados desde el carrito."], ["Migración de Vercel a Cloudflare", "El sitio se migró desde Vercel (funciones serverless + Vercel Blob) a Workers + R2 con scripts propios de exportación y carga, manteniendo intactos el diseño, el catálogo y el panel. El dominio canónico www se fijó con redirección 301 desde el dominio raíz."]],
    results: ["Más de 360 unidades en stock administradas desde el panel", "Hosting y almacenamiento sin servidor dedicado", "Editor de bordados integrado como herramienta adicional"],
    name: 'Trabalengua', domain: 'trabalengua.cl', url: 'https://www.trabalengua.cl/', type: 'E-commerce escolar',
    summary: 'Tienda de uniformes escolares con catálogo por colegio, stock por talla y un proceso de compra claro.',
    built: ['Catálogo por establecimiento', 'Stock y variantes por talla', 'Carrito y registro de pedidos', 'Panel de administración propio'],
    image: '/portfolio-trabalengua.webp', alt: 'Portada actual de Trabalengua, tienda de uniformes escolares desarrollada por Luis Reyes',
    chip: 'border-rose-200 bg-rose-50 text-rose-700', glow: 'from-rose-400/25 via-orange-300/10 to-transparent',
  },
  {
    slug: '7ma-control',
    stack: ["HTML, CSS y JavaScript", "Cloudflare Pages", "Pages Functions", "Cloudflare KV", "Script de build en Node.js"],
    challenge: "Una empresa de control de plagas necesitaba aparecer en Google cuando alguien en Talca busca fumigación, desratización o sanitización, y convertir esas visitas en contactos directos.",
    sections: [["Sitio estático orientado a velocidad", "HTML, CSS y JavaScript sin framework, lo que entrega tiempos de carga muy bajos en móviles y un HTML totalmente indexable por buscadores."], ["Landings de SEO local", "Una página por servicio (control de plagas, roedores, desinfección y sanitización en Talca), cada una con su título, descripción, contenido específico y canonical propio, además de sitemap.xml y robots.txt."], ["Contenido editable con panel /admin", "El panel usa Cloudflare Pages Functions (/api/login y /api/content) que guardan el contenido en un namespace de Cloudflare KV, permitiendo actualizar textos sin tocar código."], ["Build y cabeceras de caché", "Un script de build en Node arma la carpeta de salida solo con los archivos públicos. Las reglas de caché se definieron en _headers sin solaparse, y el dominio raíz redirige con 301 hacia www para respetar el canonical."], ["Conversión por WhatsApp", "Botones de contacto directo con mensaje prellenado según el servicio, y galería de trabajos reales para generar confianza."]],
    results: ["Una landing indexable por cada servicio", "Verificación en Google Search Console", "Cero dependencias de frameworks en el sitio público"],
    name: '7ma Control', domain: '7macontrol.cl', url: 'https://www.7macontrol.cl/', type: 'Servicios + SEO local',
    summary: 'Sitio comercial para una empresa de control de plagas, enfocado en explicar servicios y generar solicitudes.',
    built: ['Páginas por servicio', 'SEO local para Talca', 'Solicitud directa por WhatsApp', 'Galería de trabajos reales'],
    image: '/portfolio-7ma-control.webp', alt: 'Portada actual de 7ma Control, sitio de control de plagas desarrollado por Luis Reyes',
    chip: 'border-red-200 bg-red-50 text-red-700', glow: 'from-red-400/20 via-amber-300/10 to-transparent',
  },
  {
    slug: 'munay-cueros-chile',
    stack: ["HTML, CSS y JavaScript vanilla", "Generador estático en Node.js", "Cloudflare Pages", "Pages Functions", "Cloudflare R2"],
    challenge: "Una fábrica familiar de muebles en cuero y maderas nobles tenía su catálogo completo en PDF. Había que transformarlo en un sitio navegable, rápido y bien posicionado, donde cada modelo tuviera su propia ficha y el cliente pudiera cotizar.",
    sections: [["Una sola fuente de datos", "Todo el catálogo (127 modelos en 10 categorías, con nombres, precios y especificaciones) vive en un único archivo de datos. Los modelos con varias medidas o tipos de cuero incluyen sus configuraciones y se muestran con precio \"desde\"."], ["Generador estático propio", "Un script en Node recorre el catálogo y genera todas las páginas: una por categoría, una ficha por modelo, páginas de marca, la 404 y el sitemap.xml. Cada página sale con su título, descripción y datos estructurados."], ["Cotización con carrito", "El visitante arma una lista de muebles y la envía como solicitud de cotización, pensado para productos a medida donde el precio final se conversa."], ["Funciones en el borde", "Pages Functions sirven el catálogo editable y las fotos desde R2, y un middleware fuerza www como único dominio canónico conservando ruta y parámetros."], ["Diseño editorial", "Narrativa de marca y oficio con fotografía protagonista, filtros por colección y buscador de modelos en la portada."]],
    results: ["127 modelos con URL propia e indexable", "Sitemap generado automáticamente", "Sitio público 100% estático"],
    name: 'Munay Cueros Chile', domain: 'munaycueroschile.cl', url: 'https://www.munaycueroschile.cl/', type: 'Catálogo premium',
    summary: 'Experiencia editorial para una fábrica familiar de muebles en cuero y maderas nobles, con catálogo a medida.',
    built: ['Catálogo de 127 modelos', 'Filtros por colección', 'Cotización de muebles a medida', 'Narrativa de marca y oficio'],
    image: '/portfolio-munay.webp', alt: 'Portada actual de Munay Cueros Chile, catálogo de muebles desarrollado por Luis Reyes',
    chip: 'border-amber-200 bg-amber-50 text-amber-800', glow: 'from-amber-400/25 via-yellow-200/10 to-transparent',
  },
  {
    slug: 'escuela-rdlf',
    stack: ["React (CRA + craco)", "Tailwind CSS + shadcn/ui", "Cloudflare Pages Functions", "Cloudflare D1 (SQLite)", "Cloudflare R2"],
    challenge: "La Escuela de Fútbol Ronald De La Fuente necesitaba un sitio público para mostrar categorías, horarios y noticias, y también una forma ordenada de gestionar apoderados, jugadores, asistencia y pagos.",
    sections: [["Sitio público en React", "Categorías, planteles, horarios, ubicaciones, galería, noticias, auspiciadores y formulario de inscripción, construido con React, Tailwind y shadcn/ui."], ["Intranet para familias, profesores y administración", "En /intranet cada perfil ve su propio panel: las familias informan asistencia y actualizan datos, los profesores registran citaciones y la administración gestiona matrículas, planes y conciliación de pagos."], ["Base de datos relacional D1", "El backend corre en Cloudflare Pages Functions sobre D1 (SQLite), con un esquema versionado en más de 30 migraciones SQL y scripts propios para aplicarlas y respaldar la base."], ["Seguridad", "Sesiones con cookie HttpOnly y token en base de datos, contraseñas con PBKDF2-SHA256 y límite de intentos de login por cuenta e IP. Los comprobantes de transferencia y fotos se guardan en R2."], ["Pruebas y mantenimiento", "Pruebas automatizadas de la API con el runner nativo de Node y script de optimización de imágenes."]],
    results: ["Sitio público + sistema de gestión en un solo proyecto", "Esquema de datos versionado con migraciones", "Pruebas automatizadas de la API"],
    name: 'Escuela RDLF', domain: 'escuelardlf.cl', url: 'https://www.escuelardlf.cl/', type: 'Plataforma deportiva',
    summary: 'Sitio dinámico para la Escuela Ronald De La Fuente, con información deportiva, comunidad e inscripciones.',
    built: ['Categorías y planteles', 'Horarios y ubicaciones', 'Galería, noticias y auspiciadores', 'Formulario de inscripción'],
    image: '/portfolio-rdlf.webp', alt: 'Portada actual de la Escuela de Fútbol Ronald De La Fuente desarrollada por Luis Reyes',
    chip: 'border-emerald-200 bg-emerald-50 text-emerald-700', glow: 'from-emerald-400/20 via-lime-300/10 to-transparent',
  },
  {
    slug: 'cuchillos-bravo',
    stack: ["HTML, CSS y JavaScript", "Cloudflare Workers", "Cloudflare R2", "Panel de administración propio", "Node.js (herramientas y pruebas)"],
    challenge: "Una tienda de campo en Talca (cuchillería, talabartería e indumentaria) necesitaba mostrar un catálogo amplio y cambiante, y que su dueño pudiera cargar productos, fotos y videos por su cuenta.",
    sections: [["Catálogo multicategoría", "Categorías de cuchillería, talabartería, indumentaria y otros, con buscador, fichas de producto, ofertas y páginas institucionales. Hecho en HTML, CSS y JavaScript sin framework para máxima velocidad."], ["Worker con rutas propias", "Un Cloudflare Worker sirve los estáticos y atiende las rutas de producto y catálogo, además de la API del panel: productos, clientes, reseñas, informes, subida de fotos y videos, y respaldos."], ["Datos y medios en R2", "Productos, fotos y videos se guardan en Cloudflare R2, sin dependencia de servicios externos de almacenamiento."], ["Panel pensado para no perder datos", "El guardado del panel incluye historial y fusión de cambios en conflicto, para que el trabajo del dueño nunca se sobrescriba por error."], ["Compra asistida", "Carrito que prepara el pedido y lo deriva a una conversación directa, ideal para productos donde el cliente suele consultar antes de comprar."]],
    results: ["Catálogo administrado por el propio cliente", "Respaldos verificables del proyecto", "Pruebas automatizadas de las herramientas"],
    name: 'Cuchillos Bravo', domain: 'cuchillosbravo.cl', url: 'https://www.cuchillosbravo.cl/', type: 'Tienda y catálogo',
    summary: 'Catálogo comercial para una tienda de campo en Talca, con categorías, productos y compra asistida.',
    built: ['Catálogo multicategoría', 'Búsqueda y fichas de producto', 'Carrito con compra asistida', 'Identidad visual de marca'],
    image: '/portfolio-cuchillos-bravo.webp', alt: 'Portada actual de Cuchillos Bravo, tienda de campo desarrollada por Luis Reyes',
    chip: 'border-orange-200 bg-orange-50 text-orange-800', glow: 'from-orange-400/20 via-amber-200/10 to-transparent',
  },
  {
    slug: 'psicologa-andrea-martinez',
    stack: ["React (CRA + craco)", "Tailwind CSS + shadcn/ui", "Cloudflare Pages", "Pages Functions", "Cloudflare R2"],
    challenge: "Una psicóloga clínica necesitaba una presencia profesional que transmitiera cercanía, explicara su enfoque y modalidades de atención, y facilitara que un paciente la contactara o agendara.",
    sections: [["Landing en React", "Sitio construido con React, Tailwind y shadcn/ui, con una paleta cálida y tipografía cuidada para transmitir confianza desde la primera pantalla."], ["Contenido para decidir", "Secciones de servicios y especialidades, enfoque terapéutico, experiencia, testimonios y preguntas frecuentes, ordenadas para responder las dudas típicas antes de la primera sesión."], ["Precios administrables", "Los valores se editan desde un panel /admin y se guardan en un bucket privado de Cloudflare R2 mediante Pages Functions, sin necesidad de volver a publicar el sitio."], ["SEO local", "Metadatos y contenido orientados a búsquedas por modalidad (online y presencial) y ciudad."], ["Contacto directo", "Agenda y contacto por WhatsApp accesibles en todo momento, además de una página de enlaces para redes sociales."]],
    results: ["Precios actualizables sin programador", "Despliegue en Cloudflare Pages", "Diseño alineado a la identidad de la profesional"],
    name: 'Psicóloga Andrea Martínez', domain: 'psicoandreamartinez.cl', url: 'https://www.psicoandreamartinez.cl/', type: 'Marca profesional',
    summary: 'Sitio profesional para presentar su enfoque terapéutico, experiencia y modalidades de atención con una estética cálida y cercana.',
    built: ['Servicios y especialidades', 'Agenda y contacto directo', 'Testimonios y preguntas frecuentes', 'SEO local por modalidad y ciudad'],
    image: '/portfolio-andrea.webp', alt: 'Portada actual de la psicóloga Andrea Martínez desarrollada por Luis Reyes',
    chip: 'border-stone-200 bg-stone-50 text-stone-700', glow: 'from-orange-300/20 via-rose-200/10 to-transparent',
  },
]
