export const portfolioProjects = [
  {
    slug: 'trabalengua',
    challenge: "La tienda vendía uniformes de varios colegios, cada uno con sus propias prendas y tallas. Las familias necesitaban encontrar rápido lo de su colegio, y el equipo necesitaba actualizar productos y revisar pedidos sin depender de nadie.",
    sections: [["Cada colegio, su catálogo", "La familia elige su colegio y ve solo las prendas que le corresponden. Nada de buscar entre cientos de productos que no le sirven."], ["Tallas y stock siempre al día", "Cada prenda muestra las tallas disponibles en ese momento, para que nadie pida algo que ya no queda."], ["Compra simple, de principio a fin", "Carrito claro y un proceso de pedido pensado para padres que compran desde el celular, sin pasos de más."], ["Un panel para el equipo", "Desde un panel privado el equipo agrega colegios y prendas, cambia precios, ajusta stock y revisa los pedidos que van llegando."]],
    results: ["Las familias encuentran su uniforme en pocos clics", "El equipo administra la tienda por su cuenta", "Una web rápida y estable en temporada alta"],
    name: 'Trabalengua', domain: 'trabalengua.cl', url: 'https://www.trabalengua.cl/', type: 'E-commerce escolar',
    summary: 'Tienda de uniformes escolares con catálogo por colegio, stock por talla y un proceso de compra claro.',
    built: ['Catálogo por establecimiento', 'Stock y variantes por talla', 'Carrito y registro de pedidos', 'Panel de administración propio'],
    image: '/portfolio-trabalengua.webp', alt: 'Portada actual de Trabalengua, tienda de uniformes escolares desarrollada por Luis Reyes',
    chip: 'border-rose-200 bg-rose-50 text-rose-700', glow: 'from-rose-400/25 via-orange-300/10 to-transparent',
  },
  {
    slug: '7ma-control',
    challenge: "Una empresa de control de plagas necesitaba aparecer en Google cuando alguien en Talca busca fumigación o desratización, y convertir esas visitas en llamados y mensajes.",
    sections: [["Una página para cada servicio", "Control de plagas, roedores, desinfección y sanitización tienen su propia página, explicada en palabras simples y pensada para aparecer en Google."], ["Pensada para búsquedas locales", "Los contenidos están orientados a quienes buscan el servicio en Talca y la región, que es justamente el cliente que la empresa quiere atender."], ["Contacto en un clic", "Botones de WhatsApp en cada sección, con el mensaje ya preparado según el servicio que la persona está viendo."], ["Confianza desde el primer vistazo", "Galería de trabajos reales y textos que explican cómo se trabaja, para que el cliente sepa qué esperar antes de escribir."], ["Textos editables", "La empresa puede actualizar los contenidos principales desde un panel sencillo, sin tocar nada técnico."]],
    results: ["Presencia clara en Google para cada servicio", "Más consultas directas por WhatsApp", "Una web rápida, incluso con señal débil"],
    name: '7ma Control', domain: '7macontrol.cl', url: 'https://www.7macontrol.cl/', type: 'Servicios + SEO local',
    summary: 'Sitio comercial para una empresa de control de plagas, enfocado en explicar servicios y generar solicitudes.',
    built: ['Páginas por servicio', 'SEO local para Talca', 'Solicitud directa por WhatsApp', 'Galería de trabajos reales'],
    image: '/portfolio-7ma-control.webp', alt: 'Portada actual de 7ma Control, sitio de control de plagas desarrollado por Luis Reyes',
    chip: 'border-red-200 bg-red-50 text-red-700', glow: 'from-red-400/20 via-amber-300/10 to-transparent',
  },
  {
    slug: 'munay-cueros-chile',
    challenge: "Una fábrica familiar de muebles en cuero y maderas nobles tenía todo su catálogo en un PDF. Querían una web a la altura de su oficio, donde cada mueble se luciera y el cliente pudiera pedir una cotización fácilmente.",
    sections: [["Del PDF a un catálogo navegable", "Los 127 modelos del catálogo pasaron a la web, ordenados en 10 categorías con sus fotos, medidas y precios."], ["Cada mueble con su propia página", "Cada modelo tiene su ficha, con toda su información, lo que además ayuda a que Google los muestre cuando alguien los busca."], ["Cotización a medida", "El cliente arma una lista con los muebles que le interesan y la envía como solicitud de cotización, ideal para productos que se conversan antes de comprar."], ["Una marca con historia", "Secciones dedicadas al oficio, la línea de productos y los trabajos a medida, con un diseño editorial que transmite calidad."]],
    results: ["Todo el catálogo disponible en línea", "Cotizaciones ordenadas en vez de mensajes sueltos", "Una imagen de marca premium"],
    name: 'Munay Cueros Chile', domain: 'munaycueroschile.cl', url: 'https://www.munaycueroschile.cl/', type: 'Catálogo premium',
    summary: 'Experiencia editorial para una fábrica familiar de muebles en cuero y maderas nobles, con catálogo a medida.',
    built: ['Catálogo de 127 modelos', 'Filtros por colección', 'Cotización de muebles a medida', 'Narrativa de marca y oficio'],
    image: '/portfolio-munay.webp', alt: 'Portada actual de Munay Cueros Chile, catálogo de muebles desarrollado por Luis Reyes',
    chip: 'border-amber-200 bg-amber-50 text-amber-800', glow: 'from-amber-400/25 via-yellow-200/10 to-transparent',
  },
  {
    slug: 'escuela-rdlf',
    challenge: "La Escuela de Fútbol Ronald De La Fuente necesitaba mostrar su propuesta a nuevas familias y, al mismo tiempo, ordenar la gestión diaria de jugadores, asistencia y pagos, que hasta entonces se llevaba a mano.",
    sections: [["Una web para darse a conocer", "Categorías, horarios, ubicaciones, galería, noticias y auspiciadores, todo en un sitio que invita a inscribirse."], ["Inscripción en línea", "Las familias interesadas postulan desde la web, y la escuela recibe los datos ordenados."], ["Portal privado para familias", "Cada familia entra con su cuenta para avisar inasistencias, actualizar sus datos y ver la información de su hijo o hija."], ["Herramientas para profesores y administración", "Asistencia, citaciones, matrículas y pagos quedan registrados en un solo lugar, en vez de planillas y mensajes dispersos."], ["Información protegida", "Los datos de las familias y los jugadores están resguardados con acceso privado para cada perfil."]],
    results: ["La web y la gestión interna en un solo lugar", "Menos trabajo manual para la administración", "Familias mejor informadas"],
    name: 'Escuela RDLF', domain: 'escuelardlf.cl', url: 'https://www.escuelardlf.cl/', type: 'Plataforma deportiva',
    summary: 'Sitio dinámico para la Escuela Ronald De La Fuente, con información deportiva, comunidad e inscripciones.',
    built: ['Categorías y planteles', 'Horarios y ubicaciones', 'Galería, noticias y auspiciadores', 'Formulario de inscripción'],
    image: '/portfolio-rdlf.webp', alt: 'Portada actual de la Escuela de Fútbol Ronald De La Fuente desarrollada por Luis Reyes',
    chip: 'border-emerald-200 bg-emerald-50 text-emerald-700', glow: 'from-emerald-400/20 via-lime-300/10 to-transparent',
  },
  {
    slug: 'cuchillos-bravo',
    challenge: "Una tienda de campo en Talca (cuchillería, talabartería e indumentaria) tenía un catálogo amplio que cambia seguido. Su dueño necesitaba mostrarlo bien y poder actualizarlo él mismo.",
    sections: [["Catálogo completo y ordenado", "Productos organizados por categorías, con buscador, fichas detalladas y sección de ofertas."], ["Pedido asistido", "El cliente arma su carrito y termina la compra conversando directamente con la tienda, como prefieren muchos de sus clientes."], ["Panel para el dueño", "Agregar productos, cambiar precios y subir fotos o videos se hace desde un panel pensado para usarse sin conocimientos técnicos."], ["Cambios sin miedo a perder nada", "El panel guarda un historial de cambios, para que ningún ajuste se pierda por error."], ["Identidad de campo", "Un diseño que refleja el carácter de la tienda y su trayectoria en Talca."]],
    results: ["El dueño actualiza su catálogo por su cuenta", "Clientes que encuentran rápido lo que buscan", "Una tienda en línea con la personalidad del local"],
    name: 'Cuchillos Bravo', domain: 'cuchillosbravo.cl', url: 'https://www.cuchillosbravo.cl/', type: 'Tienda y catálogo',
    summary: 'Catálogo comercial para una tienda de campo en Talca, con categorías, productos y compra asistida.',
    built: ['Catálogo multicategoría', 'Búsqueda y fichas de producto', 'Carrito con compra asistida', 'Identidad visual de marca'],
    image: '/portfolio-cuchillos-bravo.webp', alt: 'Portada actual de Cuchillos Bravo, tienda de campo desarrollada por Luis Reyes',
    chip: 'border-orange-200 bg-orange-50 text-orange-800', glow: 'from-orange-400/20 via-amber-200/10 to-transparent',
  },
  {
    slug: 'psicologa-andrea-martinez',
    challenge: "Una psicóloga clínica necesitaba una presencia profesional que transmitiera cercanía, explicara su forma de trabajar y facilitara que un paciente diera el primer paso para contactarla.",
    sections: [["Una primera impresión cálida", "Diseño y colores pensados para transmitir confianza y calma desde la primera pantalla."], ["Todo lo que un paciente se pregunta", "Servicios, enfoque terapéutico, experiencia, testimonios y preguntas frecuentes, ordenados para responder las dudas antes de la primera sesión."], ["Contacto sin fricción", "WhatsApp y agenda siempre a mano, para que pedir una hora sea fácil."], ["Precios que ella misma actualiza", "Los valores de las sesiones se cambian desde un panel privado, sin tener que pedírselo a nadie."], ["Visible en Google", "Contenido orientado a quienes buscan atención psicológica online o presencial en su ciudad."]],
    results: ["Una presencia profesional y cercana", "Contacto más fácil para nuevos pacientes", "Información siempre actualizada"],
    name: 'Psicóloga Andrea Martínez', domain: 'psicoandreamartinez.cl', url: 'https://www.psicoandreamartinez.cl/', type: 'Marca profesional',
    summary: 'Sitio profesional para presentar su enfoque terapéutico, experiencia y modalidades de atención con una estética cálida y cercana.',
    built: ['Servicios y especialidades', 'Agenda y contacto directo', 'Testimonios y preguntas frecuentes', 'SEO local por modalidad y ciudad'],
    image: '/portfolio-andrea.webp', alt: 'Portada actual de la psicóloga Andrea Martínez desarrollada por Luis Reyes',
    chip: 'border-stone-200 bg-stone-50 text-stone-700', glow: 'from-orange-300/20 via-rose-200/10 to-transparent',
  },
  {
    slug: 'rz-jugueteria',
    challenge: "Una juguetería de Talca vendía con una tienda en línea lenta y difícil de mantener. Necesitaban una tienda rápida, fácil de administrar y lista para recibir pagos en línea.",
    sections: [["Todo el catálogo, renovado", "Los productos y fotos de la tienda anterior se trasladaron a la nueva, con imágenes optimizadas para cargar rápido."], ["Encontrar el juguete ideal", "Secciones con filtros por categoría y edad, buscador y fichas de producto claras."], ["Pago en línea seguro", "El pago se hace a través de Webpay, la plataforma que los clientes chilenos ya conocen. La tienda nunca ve los datos de la tarjeta."], ["Panel para el negocio", "Productos, inventario y pedidos se administran desde un panel propio."], ["Envíos y retiro", "Opciones de envío a todo Chile o retiro en Talca, coordinadas de forma directa."]],
    results: ["Una tienda más rápida que la anterior", "Administración simple para el negocio", "Preparada para vender en línea con pago seguro"],
    name: 'RZ Juguetería', domain: 'RZ Juguetería', url: 'https://rzjugueteria.psi-luisreyes.workers.dev/', type: 'E-commerce de juguetes',
    summary: 'Tienda online para una juguetería de Talca, con juguetes, material sensorial y educativo, y pago seguro con Webpay.',
    built: ['Catálogo por categoría y edad', 'Guía según lo que quieres potenciar', 'Carrito y pago con Webpay', 'Envíos a Chile y retiro en Talca'],
    image: '/portfolio-rz-jugueteria.webp', alt: 'Portada actual de RZ Juguetería, tienda de juguetes en Talca desarrollada por Luis Reyes',
    chip: 'border-pink-200 bg-pink-50 text-pink-700', glow: 'from-pink-400/20 via-teal-300/10 to-transparent',
  },
]

// srcSet con las versiones de 480 y 800 px (scripts/create-responsive-images.mjs).
export const srcSetFor = (image) => {
  const base = image.replace(/\.webp$/, '')
  return `${base}-480.webp 480w, ${base}-800.webp 800w, ${image} 1200w`
}
